### ISSUE TITLE
iPhone pictures are not automatically rotated 

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#12]
Device: iPad mini
System: ios 6.1.3
Browser: Safari and Chrome

Scenario: 
1/ Connecting on my photos with at least one album available with iPhone pictures
2/ Clic on the album
3/ Clic on a picture that doesn't seem to be rotated

Expected: 
As a thumbnail and in picture view, iPhone picture is "normally" displayed (without having to "turn the head")

Actual behavior:
In thumbnail and picture view, iPhone pictures are shown depending on the way they were taken.

**Comment by alexylem** [comment]
rotation now fixed, but:
1) need to reset library (missing feature for now, can be done manually by removing the .myphoto/previews&thumbs folders in albums)
2) update library on all albums
3) clear browser cache to see updated photos
