### ISSUE TITLE
New feature - Be able to modify one user 

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#14]
Today we can only delete / add a contact. 
It would be great to be able to change a user's "pseudo", his email, modify the group he belongs to.

**Comment by alexylem** [comment]
Ok ability to update people

**Comment by alexylem** [comment]
Now possible to update user by clicking on pen icon.
Caution: it actually deletes the user and pre-populates the add-user form. So don't forget to submit before closing the popup.
I'm currently working on a better solution (inline edition).

**Comment by alexylem** [comment]
Inline edition implemented. Click on a field to update inline an existing person.
