### ISSUE TITLE
Navigation arrows style for first and last picture

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#20]
Device: computer Dell
System: windows 7
Browser: Chrome

Scenario: 
1/ Connecting on my photos with at least one album available
2/ Click on one album with at least two pictures
3/ Click on first picture
4/ Click on the right arrow until last picture is reached

Expected: 
The right arrow is not clickable and appear with different style OR is not displayed.

Actual behavior:
The right arrow is not clickable but seems to keep same style. We thus don't realize we reached the end of the album.

Note: Same issue in the other way round (for left arrow on first picture of the album)

**Comment by alexylem** [comment]
@NolwennMely can you provide a screenshot please?

**Comment by NolwennMely** [comment]
![arrowsstyle](https://cloud.githubusercontent.com/assets/11950348/7453705/7de8239a-f26c-11e4-9125-febaa4dd7017.png)

There's a difference (less light on the button) but it's not obvious.

**Comment by alexylem** [comment]
The style is different (although not very), and is vanilla (bootstrap disabled).
I can hide it instead, @NolwennMely what do you think ?

**Comment by alexylem** [comment]
implemented, now hidden if first or last picture.
