### ISSUE TITLE
"Se connecter avec Google" doesn't seem to be clickable on firefox

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#21]
Device: computer Dell
System: windows 7
Browser: Firefox

Scenario: 
1/ Open myPhotos 
2/ Click on "Se connecter avec Google" to log in

Expected: 
The form to connect with Google is displayed

Actual behavior:
The button doesn't seem to work. Nothing happens. (neither on "G+" nor on the text)

**Comment by alexylem** [comment]
![screenshot at mai 04 13-56-16](https://cloud.githubusercontent.com/assets/11017174/7453040/5b9965e4-f265-11e4-85d3-cee94714b0c0.png)

Works on firefox for mac.
@NolwennMely could you please clear cache and try again?

**Comment by alexylem** [comment]
Also works on Firefox 37 for Windows at 1A.
Closing the issue as not reproducible.
