### ISSUE TITLE
One of my album remains at the end even after updating the date to today

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#25]
I'm not sure where the bug comes from, if this is an issue in this specific album or if this is a more general bug that happens in very specific case.
You may want to check "Album Valentin", it keeps appearing at the end when the date is set to today.

**Comment by alexylem** [comment]
The mentionned album is at the beginning of the list and looks like it is in line with the date. Can you please provide example/screenshot?

**Comment by NolwennMely** [comment]
Yesterday I did several refresh and never saw it at the beginning. This morning it indeed seems to be fixed. I'm not sure why this was misbehaving... 
We can close the issue as unreproducible.
