### ISSUE TITLE
Stretched thumbnails and full picture view

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#3]
Device: iPad mini
System: ios 6.1.3

Scenario: 
1/ Connecting on my photos with access to at least one album.
2/ Choose one album containing at least one picture with portrait view

Expected: 
Thumbnails are resized without stretching

Actual behavior:
Thumbnails are stretched

**Comment by NolwennMely** [comment]
Device: iPad mini
System: ios 6.1.3

Scenario: 
1/ Connecting on my photos with access to at least one album
2/ Choose one album containing at least one picture in portrait view
3/ Clic on a portrait view picture

Expected: 
Picture is shown, adapting to the screen size, without stretching

Actual behavior:
Picture is stretched

**Comment by alexylem** [comment]
object-fit not supported on old browsers, replacing with background-size...

**Comment by alexylem** [comment]
Fixed
