### ISSUE TITLE
Need to clic twice on menu buttons with tooltip

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#4]
Device: iPad mini
System: ios 6.1.3

Scenario: 
1/ Connecting on my photos with access to at least one album
2/ Go into one album
3/ Clic on one picture
4/ Clic on download picture icon in top menu

Expected: 
Download picture menu (big, original) is opened

Actual behavior:
Tooltip is shown. We need to clic twice to see the menu.

**Comment by alexylem** [comment]
Linked to #5

**Comment by alexylem** [comment]
removed tooltips on touch devices
