### ISSUE TITLE
After Clic, button stays in "on Click" style

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#5]
Device: iPad mini
System: ios 6.1.3

Scenario: 
1/ Connecting on my photos 
2/ Clic on "my" menu
3/ Close "my" menu

Expected: 
"My" menu comes back to normal (not clicked) design

Actual behavior:
"My" menu is still shown with "on Clic" design

**Comment by alexylem** [comment]
closed as duplicate with #7
