### ISSUE TITLE
"Soon available" buttons can't be closed

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#6]
Device: iPad mini
System: ios 6.1.3

Scenario: 
1/ Connecting on my photos with at least one album available
2/ Clic on one album
3/ Clic on download top menu button
4/ Close (try to) download top menu button

Expected: 
Download top menu button is closed (tooltip is hidden again)

Actual behavior:
After clicking once to open download top menu button, it's tooltip is shown and there's no way to close it (neither by clicking on the download icon nor by clicking somewhere else)

**Comment by alexylem** [comment]
removed tooltips on touch devices
