### ISSUE TITLE
UI is in 2 languages 

### ISSUE THREAD

**Issue by NolwennMely** [alexylem/myphotos#8]
Device: iPad mini
System: ios 6.1.3
Browser: Safari and Chrome

Scenario: 
1/ Connecting on my photos with at least one album available
2/ Clic on one album
3/ Clic on one photo
4/ Clic on menu buttons on the right

Expected: 
All UI wordings are using the same language (and ideally UI is available in several languages)

Actual behavior:
UI buttons on the left are in French, UI buttons on the right are in English.

**Comment by alexylem** [comment]
setting up multi-language support...

**Comment by alexylem** [comment]
Now available in English & French (except admin features for now only in english)
